version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bran-postgres
    environment:
      POSTGRES_DB: bran_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5131:5131"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
